Nawabali-project/Nawabali-BE

nawabali/src/main/java/com/nawabali/nawabali/config/PasswordConfig.java
nawabali/src/main/java/com/nawabali/nawabali/constant/Category.java
nawabali/src/main/java/com/nawabali/nawabali/controller/UserContoller.java
nawabali/src/main/java/com/nawabali/nawabali/domain/User.java
nawabali/src/main/java/com/nawabali/nawabali/dto/UserDto.java
nawabali/src/main/java/com/nawabali/nawabali/exception/CustomException.java
nawabali/src/main/java/com/nawabali/nawabali/exception/ErrorCode.java
nawabali/src/main/java/com/nawabali/nawabali/exception/ErrorResponse.java
nawabali/src/main/java/com/nawabali/nawabali/exception/GlobalExceptionAdvice.java
nawabali/src/main/java/com/nawabali/nawabali/jwt/JwtUtil.java
nawabali/src/main/java/com/nawabali/nawabali/repository/UserRepository.java
nawabali/src/main/java/com/nawabali/nawabali/service/UserService.java
nawabali/src/main/resources/application.properties

초기 프로젝트 세팅

---

nawabali/build.gradle
nawabali/src/main/java/com/nawabali/nawabali/constant/Address.java
nawabali/src/main/java/com/nawabali/nawabali/constant/Town.java
nawabali/src/main/java/com/nawabali/nawabali/controller/PostController.java
nawabali/src/main/java/com/nawabali/nawabali/domain/Post.java
nawabali/src/main/java/com/nawabali/nawabali/domain/image/PostImage.java
nawabali/src/main/java/com/nawabali/nawabali/dto/PostDto.java
nawabali/src/main/java/com/nawabali/nawabali/exception/ErrorCode.java
nawabali/src/main/java/com/nawabali/nawabali/s3/AwsS3Config.java
nawabali/src/main/java/com/nawabali/nawabali/s3/AwsS3Service.java
nawabali/src/main/java/com/nawabali/nawabali/service/PostService.java
nawabali/src/main/java/com/nawabali/nawabali/service/UserService.java

#16 
- 게시물 CRUD 구현
- 게시물 업로드 시 여러장 이미지 업로드를 구현하였습니다. 
- 전체 게시물을 조회할 경우 무한 스크롤이 필요하여 그 부분은 후에 구현해보겠습니다.

FEAT : 게시물 CRUD / 게시물 업로드 시 여러장 이미지 업로드

---

nawabali/src/main/java/com/nawabali/nawabali/config/WebSecurityConfig.java
nawabali/src/main/java/com/nawabali/nawabali/controller/UserController.java
nawabali/src/main/java/com/nawabali/nawabali/security/Jwt/JwtAuthenticationFilter.java
nawabali/src/main/java/com/nawabali/nawabali/security/Jwt/JwtAuthorizationFilter.java
nawabali/src/main/java/com/nawabali/nawabali/security/Jwt/JwtUtil.java
nawabali/src/main/resources/application.properties

refreshToken 구현
- 로그인 시도시 access와 refresh 발급. header와 cookie에 저장.
- refresh는 redis에 access, refresh 토큰값을 key, value 로 저장.
- 만료된 access는 refresh토큰으로 갱신시 **access와  refresh를 새로 발급하고 기존의  refresh삭제**하는 로직 추가.
-  access , refresh 10분, 30분 만료기한 수정.

refreshToken 구현

---

nawabali/src/main/generated/com/nawabali/nawabali/domain/QBookMark.java
nawabali/src/main/generated/com/nawabali/nawabali/domain/QPost.java
nawabali/src/main/generated/com/nawabali/nawabali/domain/QUser.java
nawabali/src/main/java/com/nawabali/nawabali/controller/BookMarkController.java
nawabali/src/main/java/com/nawabali/nawabali/controller/PostController.java
nawabali/src/main/java/com/nawabali/nawabali/domain/BookMark.java
nawabali/src/main/java/com/nawabali/nawabali/domain/Comment.java
nawabali/src/main/java/com/nawabali/nawabali/domain/Post.java
nawabali/src/main/java/com/nawabali/nawabali/domain/User.java
nawabali/src/main/java/com/nawabali/nawabali/dto/BookMarkDto.java
nawabali/src/main/java/com/nawabali/nawabali/dto/CommentDto.java
nawabali/src/main/java/com/nawabali/nawabali/dto/PostDto.java
nawabali/src/main/java/com/nawabali/nawabali/dto/UserDto.java
nawabali/src/main/java/com/nawabali/nawabali/exception/ErrorCode.java
nawabali/src/main/java/com/nawabali/nawabali/repository/BookMarkRepository.java
nawabali/src/main/java/com/nawabali/nawabali/repository/CommentRepository.java
nawabali/src/main/java/com/nawabali/nawabali/service/BookMarkService.java
nawabali/src/main/java/com/nawabali/nawabali/service/LikeService.java
nawabali/src/main/java/com/nawabali/nawabali/service/PostService.java
nawabali/src/main/java/com/nawabali/nawabali/service/UserService.java

- close #33 
- 북마크 등록 
- 유저의 북마크 조회(리스트)
- 유저의 북마크 조회 기능을 어느 서비스에 둘까 고민을 하다가 북마크 관련 기능은 일단 북마크관련 서비스에 두는 것이 나을 것 같다는 생각에 북마크쪽에 구현을 해두었습니다. 추후 리펙토링때 수정하여도 될 것 같아요.

Feat : 북마크 토글 형태 / 유저 북마크 조회 기능 구현

---

nawabali/src/main/generated/com/nawabali/nawabali/domain/QUser.java
nawabali/src/main/java/com/nawabali/nawabali/config/WebSecurityConfig.java
nawabali/src/main/java/com/nawabali/nawabali/constant/Address.java
nawabali/src/main/java/com/nawabali/nawabali/controller/KakaoController.java
nawabali/src/main/java/com/nawabali/nawabali/controller/UserController.java
nawabali/src/main/java/com/nawabali/nawabali/domain/User.java
nawabali/src/main/java/com/nawabali/nawabali/dto/KakaoDto.java
nawabali/src/main/java/com/nawabali/nawabali/dto/PostDto.java
nawabali/src/main/java/com/nawabali/nawabali/dto/UserDto.java
nawabali/src/main/java/com/nawabali/nawabali/repository/UserRepository.java
nawabali/src/main/java/com/nawabali/nawabali/security/Jwt/JwtUtil.java
nawabali/src/main/java/com/nawabali/nawabali/service/KakaoService.java
nawabali/src/main/resources/static/css/style.css
nawabali/src/main/resources/static/js/basic.js
nawabali/src/main/resources/templates/login.html

- close #25 카카오 로그인
- 카카오 서버에 토큰을 요청하여 카카오엑세스 토큰을 발급받고 사용자 정보를 얻습니다.
- 로그인이 인가되면 엑세스토큰과 리프레시토큰을 발급받고 redis에 저장하였습니다. 
@juwum12 님의 도움으로 구현할 수 있었습니다. 감사합니다.

Feat : 카카오 로그인

---

nawabali/src/main/java/com/nawabali/nawabali/controller/BookMarkController.java
nawabali/src/main/java/com/nawabali/nawabali/controller/CommentController.java
nawabali/src/main/java/com/nawabali/nawabali/controller/EmailController.java
nawabali/src/main/java/com/nawabali/nawabali/controller/LikeController.java
nawabali/src/main/java/com/nawabali/nawabali/controller/PostController.java
nawabali/src/main/java/com/nawabali/nawabali/controller/UserController.java
nawabali/src/main/java/com/nawabali/nawabali/controller/UserImageController.java
nawabali/src/main/java/com/nawabali/nawabali/exception/ErrorCode.java
nawabali/src/main/java/com/nawabali/nawabali/s3/AwsS3Service.java
nawabali/src/main/java/com/nawabali/nawabali/service/ImageService.java
nawabali/src/main/java/com/nawabali/nawabali/service/UserService.java

- PR 내용
1. 사용자 프로필 관련 코드를 userImage 관련 클래스로 분리하였습니다.
2. 스웨거관련 어노테이션을 controller에 적용하였습니다. 
3. 사용하지 않는 주석 및 코드 제거

fix : 코드 리펙토링 및 스웨거 설명

---

src/main/generated/com/nawabali/nawabali/domain/QPost.java
src/main/java/com/nawabali/nawabali/controller/ChatRoomController.java
src/main/java/com/nawabali/nawabali/controller/CommentController.java
src/main/java/com/nawabali/nawabali/controller/EmailController.java
src/main/java/com/nawabali/nawabali/domain/Post.java
src/main/java/com/nawabali/nawabali/dto/PostDto.java
src/main/java/com/nawabali/nawabali/dto/dslDto/CommentDslDto.java
src/main/java/com/nawabali/nawabali/dto/dslDto/PostDslDto.java
src/main/java/com/nawabali/nawabali/repository/dslrepository/PostDslRepositoryCustomImpl.java
src/main/java/com/nawabali/nawabali/service/BookMarkService.java
src/main/java/com/nawabali/nawabali/service/LikeService.java
src/main/java/com/nawabali/nawabali/service/PostService.java
src/test/java/com/nawabali/nawabali/repository/PostDslRepositoryCustomImplTest.java

- FE 에서 게시물에 title이 필요하지 않다고 하여 title 이 들어간 부분들을 수정하였습니다. 
- 그 밖에 간단한 코드 수정
.
.
코드를 수정하면서 사용되지 않고 있는 주석들 및 메서드들이 있었는데 작업 하시면서 필요없는 주석이나 메서드는 삭제해주시면 감사하겠습니다!
혹시 나중에 필요한 코드라면 PR 올려주실 때 그에대한 언급을 따로 해주시면 이해하는데 더 좋을 것 같습니다.

FEAT : FE 요구사항에 따른 수정

---

src/main/java/com/nawabali/nawabali/config/MultipartJackson2HttpMessageConverter.java
src/main/java/com/nawabali/nawabali/controller/PostController.java

현재 게시물 사진 업로드가 postman에서는 정상 동작하지만 swagger와  FE 에서 작동하지 않아 수정하였습니다. 
- 변경사항
1. 게시물 생성 시 사진 업로드 부분 @RequestPart 로 변경
2. MultipartJackson2HttpMessageConverter 파일 추가

Fix :  Post 사진 업로드 수정

---

.idea/dataSources.xml
src/main/java/com/nawabali/nawabali/config/WebSocketConfig.java
src/main/java/com/nawabali/nawabali/constant/MessageType.java
src/main/java/com/nawabali/nawabali/controller/ChatController.java
src/main/java/com/nawabali/nawabali/controller/ChatRoomController.java
src/main/java/com/nawabali/nawabali/controller/NotificationController.java
src/main/java/com/nawabali/nawabali/domain/Chat.java
src/main/java/com/nawabali/nawabali/domain/Notification.java
src/main/java/com/nawabali/nawabali/dto/ChatDto.java
src/main/java/com/nawabali/nawabali/dto/NotiDeleteResponseDto.java
src/main/java/com/nawabali/nawabali/exception/ErrorCode.java
src/main/java/com/nawabali/nawabali/repository/ChatMessageRepository.java
src/main/java/com/nawabali/nawabali/repository/ChatRoomRepository.java
src/main/java/com/nawabali/nawabali/repository/NotificationRepository.java
src/main/java/com/nawabali/nawabali/service/ChatMessageService.java
src/main/java/com/nawabali/nawabali/service/ChatRoomService.java
src/main/java/com/nawabali/nawabali/service/NotificationService.java

swagger 주석 추가
chat/notification 프론트와 맞추기 위해 주석 정리

chat / notification 리팩토링

---

.idea/dataSources.xml
src/main/generated/com/nawabali/nawabali/domain/QBookMark.java
src/main/java/com/nawabali/nawabali/controller/BookMarkController.java
src/main/java/com/nawabali/nawabali/controller/CommentController.java
src/main/java/com/nawabali/nawabali/controller/PostController.java
src/main/java/com/nawabali/nawabali/domain/BookMark.java
src/main/java/com/nawabali/nawabali/dto/BookMarkDto.java
src/main/java/com/nawabali/nawabali/dto/querydsl/BookmarkDslDto.java
src/main/java/com/nawabali/nawabali/repository/querydsl/bookmark/BookmarkDslRepositoryCustom.java
src/main/java/com/nawabali/nawabali/repository/querydsl/bookmark/BookmarkDslRepositoryCustomImpl.java
src/main/java/com/nawabali/nawabali/service/BookMarkService.java
src/test/java/com/nawabali/nawabali/commentTest/CommentDslTest.java

- 북마크 정렬 시 생성일 필드가 필요하여 createdAt 필드 추가
- 유저의 북마크 조회 시 무한스크롤로 변경**

FIX : 유저 북마크 조회 시 무한 스크롤로 구현

---

src/main/java/com/nawabali/nawabali/controller/PostController.java
src/main/java/com/nawabali/nawabali/dto/PostDto.java
src/main/java/com/nawabali/nawabali/service/PostService.java

경일님 요청으로 
해당 구 정보 반환 -> 전체 구 리스트 반환으로 변경하였습니다.

동네별 점수 조회 _ 전체 구 리스트로 반환

---

.idea/dataSources.xml
src/main/java/com/nawabali/nawabali/domain/BookMark.java
src/main/java/com/nawabali/nawabali/domain/Post.java
src/main/java/com/nawabali/nawabali/domain/image/PostImage.java
src/main/java/com/nawabali/nawabali/dto/PostDto.java
src/main/java/com/nawabali/nawabali/service/BookMarkService.java
src/main/java/com/nawabali/nawabali/service/PostService.java

1. 게시물 조회 메소드와 유저 북마크 조회 메소드의 가독성을 위해  DTO 객체 생성 로직을 메소드로 분리

FIX : 코드 리펙토링

---

src/main/java/com/nawabali/nawabali/controller/PostController.java
src/main/java/com/nawabali/nawabali/dto/PostDto.java
src/main/java/com/nawabali/nawabali/service/PostService.java

경일님 요청으로 게시물 상세조회시 ResponseDto에 로그인한 유저의 토글링 여부를 추가했습니다.
**로그인**
**비로그인**

FEAT : 게시물 상세 조회시 반환 값에 토글링 여부 추가.

---

.idea/dataSources.xml
src/main/java/com/nawabali/nawabali/config/WebSocketConfig.java
src/main/java/com/nawabali/nawabali/constant/ChatRoomEnum.java
src/main/java/com/nawabali/nawabali/constant/MessageType.java
src/main/java/com/nawabali/nawabali/controller/ChatRoomController.java
src/main/java/com/nawabali/nawabali/domain/Chat.java
src/main/java/com/nawabali/nawabali/dto/ChatDto.java
src/main/java/com/nawabali/nawabali/exception/ErrorCode.java
src/main/java/com/nawabali/nawabali/repository/ChatMessageRepository.java
src/main/java/com/nawabali/nawabali/repository/ChatRoomRepository.java
src/main/java/com/nawabali/nawabali/repository/UserRepository.java
src/main/java/com/nawabali/nawabali/repository/querydsl/chat/ChatDslRepositoryCustom.java
src/main/java/com/nawabali/nawabali/repository/querydsl/chat/ChatDslRepositoryCustomImpl.java
src/main/java/com/nawabali/nawabali/service/ChatMessageService.java
src/main/java/com/nawabali/nawabali/service/ChatRoomService.java
src/main/java/com/nawabali/nawabali/service/NotificationService.java
src/main/java/com/nawabali/nawabali/service/PostService.java
src/main/java/com/nawabali/nawabali/service/UserService.java

1:1 / 1:N 채팅방 생성 구분 및 본인의 채팅방 조회시 1:1 채팅방의 이름은 상대방의 nickname으로 설정
1:1 생성
1:N 생성
본인 채팅방 조회시 -> 1:1 채팅방 이름은 상대방 이름

1:1 / 1:N 채팅방 생성 구분 및 본인의 채팅방 조회시 1:1 채팅방의 이름은 상대방의 nickname으로 설정

---

src/main/java/com/nawabali/nawabali/dto/UserDto.java
src/main/java/com/nawabali/nawabali/dto/querydsl/CommentDslDto.java
src/main/java/com/nawabali/nawabali/exception/ErrorCode.java

* close #88
* 댓글 반환값에 작성자 프로필이미지, 주거지, 회원등급추가 반환
* CommentDslDto 내 ResponseDto 반환값 수정
* FE 편의를 위해 주거지 및 회원등급은 하나의 문자열로 반환
* ErrorCode에 회원등급 404 Not found 추가
* getComments

FEAT : 댓글 반환값에 작성자 프로필이미지, 주거지, 회원등급 추가 반환

---

.idea/dataSources.xml
src/main/java/com/nawabali/nawabali/domain/Chat.java
src/main/java/com/nawabali/nawabali/dto/ChatDto.java
src/main/java/com/nawabali/nawabali/dto/PostDto.java
src/main/java/com/nawabali/nawabali/exception/ErrorCode.java
src/main/java/com/nawabali/nawabali/repository/PostRepository.java
src/main/java/com/nawabali/nawabali/service/ChatMessageService.java
src/main/java/com/nawabali/nawabali/service/PostService.java

지역별 제일 많은 게시물 카테고리
&
캐스팅 오류 해결 (push 해서 합쳐졌어요!)
**오류 메세지**
발생한 오류는 java.lang.ClassCastException로, com.nawabali.nawabali.domain.User를 java.util.List로 캐스팅할 수 없다는 것을 나타냅니다. 이는 코드의 특정 부분에서 타입 캐스팅이 잘못되었음을 의미합니다.
주어진 코드에서 List<User> usersInChatRoom = (List<User>) chatRoom.getUser(); 부분에서 오류가 발생하고 있는데, 이 코드에서 chatRoom.getUser()가 반환하는 객체가 실제로 List<User> 타입이 아닌 것으로 추정됩니다. 이것이 오류의 원인일 수 있습니다.

지역별 제일 많은 게시물 카테고리 & 캐스팅 오류 해결

---

src/main/java/com/nawabali/nawabali/service/ChatMessageService.java

FIX : 채팅에 log.debug 구현

---

src/main/java/com/nawabali/nawabali/service/ChatMessageService.java
src/main/java/com/nawabali/nawabali/service/NotificationService.java

FIX : 오류로 인해 알림(SSE) 주석처리 - 오류 내용 [userSender = null]
오류는 추후 수정 예정!

FIX : 오류로 인해 알림(SSE) 주석처리 - 오류 내용 [userSender = null]

---

build.gradle
src/main/java/com/nawabali/nawabali/NawabaliApplication.java
src/main/java/com/nawabali/nawabali/dto/ChatDto.java
src/main/java/com/nawabali/nawabali/service/ChatMessageService.java

FEAT : 메세지 전송시 response 보내기 & 서버 로그 종료 방지 코드 추가

FEAT : 메세지 전송시 response 보내기 & 서버 로그 종료 방지 코드 추가

---

src/main/java/com/nawabali/nawabali/controller/ChatController.java
src/main/java/com/nawabali/nawabali/service/ChatMessageService.java

FIX : 메세지 전송시 response 보내기 수정

---

src/main/java/com/nawabali/nawabali/controller/PostController.java
src/main/java/com/nawabali/nawabali/dto/PostDto.java
src/main/java/com/nawabali/nawabali/repository/querydsl/post/PostDslRepositoryCustom.java
src/main/java/com/nawabali/nawabali/repository/querydsl/post/PostDslRepositoryCustomImpl.java
src/main/java/com/nawabali/nawabali/service/PostService.java
src/test/java/com/nawabali/nawabali/postTest/PostDslTest.java

-  구를 선택하면 한 달간 각 카테고리의 게시글 개수를 반환하는 API

FEAT : 구 와 기간별 각 카테고리의 게시글 개수

---

src/main/java/com/nawabali/nawabali/service/ChatMessageService.java

FIX : 메세지 dto 보내기

---

.idea/dataSources.xml
src/main/java/com/nawabali/nawabali/constant/Address.java
src/main/java/com/nawabali/nawabali/domain/User.java
src/main/java/com/nawabali/nawabali/dto/PostDto.java
src/main/java/com/nawabali/nawabali/repository/querydsl/comment/CommentDslRepositoryCustomImpl.java
src/main/java/com/nawabali/nawabali/repository/querydsl/post/PostDslRepositoryCustomImpl.java
src/main/java/com/nawabali/nawabali/service/PostService.java

- 동네별 점수 조회하는 서비스 로직을 간단하게 하여 가독성을 높이고자 메서드를 분리하는 리펙토링 작업을 진행하였습니다. 
- 그외 필요없는 코드 삭제 및 valid 추가

FIX :  동네별 점수 조회 메서드 리펙토링(메소드 분리)

---

.github/workflows/cicd_production.yml
appspec.yml
build.gradle
scripts/health.sh
scripts/profile.sh
scripts/start.sh
scripts/stop.sh
scripts/switch.sh
src/main/java/com/nawabali/nawabali/HelloController.java
src/main/java/com/nawabali/nawabali/ProfileController.java
src/main/java/com/nawabali/nawabali/config/WebSecurityConfig.java

* #105 
* EC2 서버 내 경로 변경되었고, 기존 경로의 파일은 무중단배포 정상 확인되면 삭제하겠습니다.
* HTTPS 적용 및 프론트엔드 서버 적용까지 시간 소요될 수 있습니다.
* 별도 리포지토리에서 무중단배포 테스트 완료하였습니다.

feat : 무중단배포 적용

---

src/main/java/com/nawabali/nawabali/controller/ChatController.java
src/main/java/com/nawabali/nawabali/dto/ChatDto.java
src/main/java/com/nawabali/nawabali/service/ChatMessageService.java
src/main/java/com/nawabali/nawabali/service/ChatRoomService.java

FIX : 메세지 dto 반환

---

src/main/java/com/nawabali/nawabali/service/ChatMessageService.java

FIX : 메세지 dto 보내기 수정

---

.idea/dataSources.xml
src/main/java/com/nawabali/nawabali/controller/ChatController.java
src/main/java/com/nawabali/nawabali/dto/ChattingRequest.java
src/main/java/com/nawabali/nawabali/service/ChatMessageService.java
src/main/java/com/nawabali/nawabali/service/ChatRoomService.java

메세지 전송 수정 했고, 데이터가 프론트쪽에 들어가는지 확인을 위한 머지입니다.
(연결 성공 ㅠㅠ)
주석은 테스트용으로 완료되면 정리하겠습니다!

FIX : 메세지 전송 수정

---

src/main/java/com/nawabali/nawabali/service/ChatMessageService.java

FIX : 메세지 전송 dto수정

---

src/main/java/com/nawabali/nawabali/config/WebSocketConfig.java
src/main/java/com/nawabali/nawabali/controller/ChatController.java
src/main/java/com/nawabali/nawabali/controller/ChatRoomController.java
src/main/java/com/nawabali/nawabali/domain/Chat.java
src/main/java/com/nawabali/nawabali/dto/ChatDto.java
src/main/java/com/nawabali/nawabali/global/websocket/WebSocketChatRoomCount.java
src/main/java/com/nawabali/nawabali/global/websocket/WebSocketEventListener.java
src/main/java/com/nawabali/nawabali/repository/ChatMessageRepository.java
src/main/java/com/nawabali/nawabali/repository/ChatRoomRepository.java
src/main/java/com/nawabali/nawabali/repository/querydsl/chat/ChatDslRepositoryCustom.java
src/main/java/com/nawabali/nawabali/repository/querydsl/chat/ChatDslRepositoryCustomImpl.java
src/main/java/com/nawabali/nawabali/security/Jwt/JwtUtil.java
src/main/java/com/nawabali/nawabali/security/Jwt/WebSocketJwtInterceptor.java
src/main/java/com/nawabali/nawabali/service/ChatMessageService.java
src/main/java/com/nawabali/nawabali/service/ChatRoomService.java

1. 채팅 연결
2. 구독
3.  메세지 보내기
&
추가로 회원가입/로그인/회원정보조회 확인했습니다!

FEAT : 채팅 인증인가 & 실시간 

---

.idea/compiler.xml
src/main/java/com/nawabali/nawabali/constant/DefaultProfileImage.java

* close #121
* 디폴트 프로필 이미지 constant 변경
* 프로필 이미지 삭제 후 기본 디폴트 이미지로 자동 변경 
* 신규 회원가입시 기본 디폴트 이미지로 자동 지정

feat : default 프로필 이미지 수정

---

src/main/java/com/nawabali/nawabali/controller/PostController.java
src/main/java/com/nawabali/nawabali/repository/querydsl/post/PostDslRepositoryCustom.java
src/main/java/com/nawabali/nawabali/repository/querydsl/post/PostDslRepositoryCustomImpl.java
src/main/java/com/nawabali/nawabali/service/PostService.java

< 프론트분들의 추가 요청 API  >
- 유저 닉네임으로 게시물 조회
**user 의 닉네임으로 그 유저의 모든 게시물을 무한스크롤로 조회** 합니다.

FEAT : 유저 닉네임으로 게시물 조회

---

src/main/java/com/nawabali/nawabali/controller/PostController.java
src/main/java/com/nawabali/nawabali/repository/querydsl/post/PostDslRepositoryCustom.java
src/main/java/com/nawabali/nawabali/repository/querydsl/post/PostDslRepositoryCustomImpl.java
src/main/java/com/nawabali/nawabali/service/PostService.java

< 프론트 요청 추가 반영 > 
* getUserPost 메소드 수정
**- 유저 id 로 게시물 조회 시 카테고리로 분류 기능 추가**

FIX : getUserPost 메소드 수정

---

.idea/dataSources.xml
src/main/java/com/nawabali/nawabali/domain/Chat.java
src/main/java/com/nawabali/nawabali/repository/querydsl/chat/ChatDslRepositoryCustomImpl.java
src/main/java/com/nawabali/nawabali/service/ChatRoomService.java

FIX : 본인 전체 채팅방 조회_최근메세지 + 프로필 사진 
전체 메세지 조회_상대방 프로필 사진 보내기 + dto 정리

FIX : 본인 전체 채팅방 조회_최근메세지 + 프로필 사진 & 전체 메세지 조회_상대방 프로필 사진 보내기 + dto 정리

---

src/main/java/com/nawabali/nawabali/constant/UserRankEnum.java
src/main/java/com/nawabali/nawabali/domain/User.java
src/main/java/com/nawabali/nawabali/dto/BookMarkDto.java
src/main/java/com/nawabali/nawabali/repository/querydsl/bookmark/BookmarkDslRepositoryCustomImpl.java
src/main/java/com/nawabali/nawabali/service/BookMarkService.java
src/main/java/com/nawabali/nawabali/service/LikeService.java
src/main/java/com/nawabali/nawabali/service/UserService.java

FIX : 북마크 조회시 반환값 수정

---

.idea/dataSources.xml
src/main/java/com/nawabali/nawabali/constant/UserRankEnum.java
src/main/java/com/nawabali/nawabali/domain/User.java
src/main/java/com/nawabali/nawabali/repository/PostRepository.java
src/main/java/com/nawabali/nawabali/service/KakaoService.java
src/main/java/com/nawabali/nawabali/service/PostService.java

FEAT : post 작성시, 등급 업그레이드 기준에 맞으면 등급업 시키기 구현

FEAT : post 작성시, 등급 업그레이드 기준에 맞으면 등급업 시키기 구현

---

.idea/compiler.xml
.idea/dataSources.xml
src/main/java/com/nawabali/nawabali/controller/PostController.java
src/main/java/com/nawabali/nawabali/domain/elasticsearch/PostSearch.java
src/main/java/com/nawabali/nawabali/repository/elasticsearch/PostSearchRepository.java
src/main/java/com/nawabali/nawabali/repository/querydsl/post/PostDslRepositoryCustom.java
src/main/java/com/nawabali/nawabali/repository/querydsl/post/PostDslRepositoryCustomImpl.java
src/main/java/com/nawabali/nawabali/service/PostService.java

* FEAT : 게시물 검색 시 반환값 추가 및 카테고리/id 로 필터링 기능 추가

FEAT : 게시물 검색 시 반환값 추가 및 카테고리/id 로 필터링 기능 추가

---

src/main/java/com/nawabali/nawabali/controller/PostController.java
src/main/java/com/nawabali/nawabali/repository/querydsl/post/PostDslRepositoryCustom.java
src/main/java/com/nawabali/nawabali/repository/querydsl/post/PostDslRepositoryCustomImpl.java
src/main/java/com/nawabali/nawabali/service/PostService.java

FIX : 게시물 검색 API 수정

---

src/main/java/com/nawabali/nawabali/controller/PostController.java
src/main/java/com/nawabali/nawabali/domain/Post.java
src/main/java/com/nawabali/nawabali/dto/PostDto.java
src/main/java/com/nawabali/nawabali/repository/elasticsearch/PostSearchRepository.java
src/main/java/com/nawabali/nawabali/repository/querydsl/post/PostDslRepositoryCustom.java
src/main/java/com/nawabali/nawabali/repository/querydsl/post/PostDslRepositoryCustomImpl.java
src/main/java/com/nawabali/nawabali/service/PostService.java
src/test/java/com/nawabali/nawabali/commentTest/CommentDslTest.java
src/test/java/com/nawabali/nawabali/service/PostSearchTest.java

- 검색기능을 ES 만 사용하여 변경하였습니다.
<변경 전>
- ES + QueryDSL 
<변경 후>
- ES 
**<변경이유>** 
**- 둘의 속도를 비교해본 결과 ES 가 빠르다는 것을 확인**
<주석>
**되어있는 주석은 테스트코드를 위해서 남겨놓았습니다.**

FEAT : 검색 기능 수정(ES만 사용)

---

.idea/compiler.xml
src/main/java/com/nawabali/nawabali/controller/NotificationController.java
src/main/java/com/nawabali/nawabali/repository/NotificationRepository.java
src/main/java/com/nawabali/nawabali/service/ChatRoomService.java
src/main/java/com/nawabali/nawabali/service/CommentService.java
src/main/java/com/nawabali/nawabali/service/LikeService.java
src/main/java/com/nawabali/nawabali/service/NotificationService.java

FIX : 알림 삭제 추가 & SSE heartbeattimeout

FIX : 알림 삭제 추가 & SSE heartbeattimeout

---

.idea/dataSources.xml
src/main/java/com/nawabali/nawabali/service/ChatMessageService.java

FIX : 메세지 연결 오류

---

.idea/dataSources.xml
src/main/java/com/nawabali/nawabali/repository/ChatMessageRepository.java
src/main/java/com/nawabali/nawabali/service/ChatMessageService.java
src/main/java/com/nawabali/nawabali/service/ChatRoomService.java
src/main/java/com/nawabali/nawabali/service/NotificationService.java

FIX : 알림 heartbeat 구현

---

.idea/compiler.xml
src/main/java/com/nawabali/nawabali/service/NotificationService.java

FIX : 에러 확인을 위한 알림 ioexception, 로그 추가

FIX : 알림 ioexception, 로그 추가

---

src/main/java/com/nawabali/nawabali/controller/ChatRoomController.java
src/main/java/com/nawabali/nawabali/domain/Chat.java
src/main/java/com/nawabali/nawabali/dto/ChatDto.java
src/main/java/com/nawabali/nawabali/repository/querydsl/chat/ChatDslRepositoryCustom.java
src/main/java/com/nawabali/nawabali/repository/querydsl/chat/ChatDslRepositoryCustomImpl.java
src/main/java/com/nawabali/nawabali/service/ChatMessageService.java
src/main/java/com/nawabali/nawabali/service/ChatRoomService.java
src/main/java/com/nawabali/nawabali/service/NotificationService.java

FIX : 채팅방 입장 
-> 채팅방 입장을 Enum 타입으로 합쳤습니다.
FIX : 특정 채팅방 조회 
현재 채팅방 조회를 채팅방 / 채팅메세지 2개를 한번에 검색하는데 채팅메세지 검색 결과가 1개만 나와서 수정했습니다
+ 페이지 네이션 적용

FIX : 채팅방 입장 & 특정 채팅방 조회 

---

src/main/java/com/nawabali/nawabali/service/ChatRoomService.java

머지한게 서버에 반영이 되지 않았습니다.
서버에 response와 로컬 response 값이 달라 동일한 코드에 주석만 달아서 다시 올립니다.

본인 전체 채팅방 목록 반환

---

.idea/dataSources.xml
src/main/java/com/nawabali/nawabali/dto/PostDto.java
src/main/java/com/nawabali/nawabali/service/PostService.java

게시물 상세보기 시 리사이즈 이미지 제외
- 상세보기 시 리사이즈 이미지가 같이 조회되는 것을 수정

FIX : 게시물 상세보기 시 리사이즈 이미지 제외

---

.idea/dataSources.xml
src/main/java/com/nawabali/nawabali/controller/ChatRoomController.java
src/main/java/com/nawabali/nawabali/dto/ChatDto.java
src/main/java/com/nawabali/nawabali/global/websocket/WebSocketEventListener.java
src/main/java/com/nawabali/nawabali/repository/querydsl/chat/ChatDslRepositoryCustom.java
src/main/java/com/nawabali/nawabali/repository/querydsl/chat/ChatDslRepositoryCustomImpl.java
src/main/java/com/nawabali/nawabali/service/ChatMessageService.java
src/main/java/com/nawabali/nawabali/service/ChatRoomService.java
src/main/java/com/nawabali/nawabali/service/NotificationService.java

- sseEmitter 연결시 안읽은 메세지 수 추가 (메인 페이지)
- 채팅방 검색 결과 dto 수정
- 메세지 ENTER 할때 빈 메세지 보내지는것 수정
- 동시 접속자 unsubscribe 연결 완료

FIX : 알림 관련 수정사항 (+unsubscribe)

---

src/main/java/com/nawabali/nawabali/controller/NotificationController.java
src/main/java/com/nawabali/nawabali/service/NotificationService.java

서버에 `Could not open JPA EntityManager for transaction` 에러로 CompletableFuture로 비동기 처리 부분 추가

bug : 알람 비동기 처리

---

src/main/java/com/nawabali/nawabali/service/NotificationService.java

bug : 알림 클라이언트와 연결이 끊어졌을때 보안 (서버 로그 확인후 수정)
FIX :  알림 보내주는 형식 수정

bug : 알림 클라이언트와 연결이 끊어졌을때 보안 & 알림 보내주는 형식 수정
